Navbar functionality
greenfox-academy/epam-jsa-black-pearl pull request #63
Opened 2017-10-24 09:47 UTC by ChiuMungZitAlexander

2017-10-24 10:03 UTC, beltekylevi requested changes
the logout icon looks like an upload icon
 - rotate the logout icon 90 degs (can be done from css)

2017-10-24 10:03 UTC, beltekylevi commented on src/client/components/boardNav/index.js
> +    window.location.href = '/boards';
https://reacttraining.com/react-router/web/api/Link

2017-10-24 14:57 UTC, ChiuMungZitAlexander commented
consider the possibility that more icon will be added in the future, i altered the pic by in the hard way~~ this may save some css class 😜

2017-10-25 01:26 UTC, beltekylevi approved these changes

2017-10-25 01:27 UTC, merged