Frontend Columns dnd
greenfox-academy/epam-jsa-black-pearl pull request #80
Opened 2017-10-30 09:41 UTC by ChiuMungZitAlexander

As backend $api is still in progress, so please just review. Or you can approve the request and after I will modify the $api ASAP. Thanks a lot😜😜😜😜😜

2017-10-30 10:06 UTC, beltekylevi commented
please move the story in jira as well, also provide the task id here thanks!

2017-10-30 10:07 UTC, beltekylevi requested changes

2017-10-30 10:07 UTC, beltekylevi commented on src/client/components/boardColumn/index.js
> +        onDragEnter={this.handleDragEnter.bind(this)}
you could bind `this` in the constructor

2017-10-30 10:07 UTC, beltekylevi commented on src/client/components/boardColumn/index.js
> +        onDragOver={this.handleDragOver.bind(this, this.props.column._id)}
you could bind `this` in the constructor

2017-10-30 10:07 UTC, beltekylevi commented on src/client/components/boardColumn/index.js
> +        onDragLeave={this.handleDragLeave.bind(this)}
you could bind `this` in the constructor

2017-10-30 10:07 UTC, beltekylevi commented on src/client/components/boardColumn/index.js
> +        onDrop={this.handleDrop.bind(this)}
you could bind `this` in the constructor

2017-10-30 10:07 UTC, beltekylevi commented on src/client/components/boardColumn/index.js
> +          onDragStart={this.handleDragStart.bind(this, this.props.column._id)}
you could bind `this` in the constructor

2017-10-30 10:07 UTC, beltekylevi commented on src/client/components/boardColumn/index.js
> +          onDrag={this.handleDrag.bind(this)}
you could bind `this` in the constructor

2017-10-30 10:07 UTC, beltekylevi commented on src/client/components/boardColumn/index.js
> +          onDragEnd={this.handleDragEnd.bind(this)}>
you could bind `this` in the constructor

2017-10-30 10:07 UTC, beltekylevi commented on src/client/components/boardDetail/index.js
> +            reorderColumns={this.reorderColumns.bind(this)} />
you could bind `this` in the constructor

2017-10-31 06:04 UTC, beltekylevi approved these changes

2017-10-31 06:05 UTC, beltekylevi commented
which story is this in jira?

2017-10-31 06:12 UTC, ChiuMungZitAlexander commented
it is blp-71 drag and drop columns frontend

2017-10-31 06:24 UTC, merged